server:
  port: 8082

spring:
  application:
    name: "product-json-consumer"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
    properties:
      schema:
        registry:
          url: http://localhost:8081
      json:
        value:
          type: dev.pravin.spring.kafka.json.model.Product
    # At application startup a missing topic on the broker will not fail the
    # application startup
    listener:
      missing-topics-fatal: false

  # Since Spring Boot 2.2 JMX is disabled by default but
  # Micrometer is depending on JMX for (Spring) Kafka consumer metrics!
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: ${spring.application.name}